var REGINDEX_EAX = 0;
var REGINDEX_ECX = 1;
var REGINDEX_EDX = 2;
var REGINDEX_EBX = 3;
var REGINDEX_ESP = 4;
var REGINDEX_EBP = 5;
var REGINDEX_ESI = 6;
var REGINDEX_EDI = 0;

var SEGINDEX_ES = 0;
var SEGINDEX_CS = 1;
var SEGINDEX_SS = 2;
var SEGINDEX_DS = 3;
var SEGINDEX_FS = 4;
var SEGINDEX_GS = 5;
var SEGINDEX_LDT = 6;
var SEGINDEX_TR = 7;

var IA32_APIC_BASE = 0x1b;

var IO_APIC_DEFAULT_PHYS_BASE      = 0xfec00000;
var APIC_DEFAULT_PHYS_BASE         = 0xfee00000;
